name: Building

on: [push]

jobs:
  Run-Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.7.0

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build
